[MeasureBand0]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=1
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand1]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=2
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand2]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=3
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand3]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=4
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand4]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=5
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand5]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=6
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand6]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=7
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand7]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=8
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand8]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=9
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand9]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=10
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand10]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=11
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand11]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=12
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand12]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=13
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand13]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=14
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand14]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=15
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand15]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=16
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand16]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=17
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand17]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=18
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand18]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=19
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand19]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=20
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand20]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=21
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand21]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=22
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand22]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=23
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand23]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=24
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand24]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=25
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand25]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=26
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand26]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=27
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand27]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=28
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand28]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=29
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand29]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=30
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand30]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=31
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand31]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=32
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand32]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=33
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand33]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=34
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand34]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=35
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand35]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=36
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand36]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=37
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand37]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=38
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand38]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=39
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand39]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=40
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand40]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=41
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand41]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=42
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand42]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=43
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand43]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=44
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand44]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=45
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand45]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=46
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand46]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=47
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand47]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=48
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand48]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=49
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand49]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=50
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand50]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=51
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand51]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=52
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand52]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=53
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand53]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=54
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand54]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=55
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand55]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=56
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand56]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=57
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand57]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=58
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand58]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=59
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand59]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=60
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand60]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=61
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand61]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=62
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand62]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=63
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand63]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=64
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand64]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=65
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand65]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=66
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand66]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=67
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand67]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=68
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand68]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=69
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand69]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=70
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand70]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=71
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand71]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=72
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand72]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=73
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand73]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=74
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand74]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=75
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand75]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=76
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand76]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=77
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand77]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=78
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand78]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=79
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)
[MeasureBand79]
Measure=Plugin
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=80
Group=Audio
UpdateDivider=(0 = 1 ? -1 : 1)
AverageSize=(#SmoothnessLevel#)